services:
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "${N8N_PORT:-5678}:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-homelab}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - WEBHOOK_URL=${WEBHOOK_URL:-http://homelab:5678/}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-Europe/Madrid}
      - TZ=${GENERIC_TIMEZONE:-Europe/Madrid}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE:-false}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - ${N8N_DATA_DIR:-/data/homelab/n8n/data}:/home/node/.n8n
      - ${N8N_FILES_DIR:-/data/homelab/n8n/files}:/files
