services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - /data/homelab/server_monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /data/homelab/server_monitoring/prometheus/data:/prometheus
    networks:
      - server-monitoring

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:latest
    restart: unless-stopped
    command:
      - --path.rootfs=/host
    pid: host
    ports:
      - "${NODE_EXPORTER_PORT:-9100}:9100"
    volumes:
      - /:/host:ro,rslave
    networks:
      - server-monitoring

  blackbox-exporter:
    container_name: blackbox-exporter
    image: prom/blackbox-exporter:latest
    restart: unless-stopped
    command:
      - --config.file=/etc/blackbox_exporter/config.yml
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /data/homelab/server_monitoring/prometheus/blackbox.yml:/etc/blackbox_exporter/config.yml:ro
    networks:
      - server-monitoring
      - adguard
      - n8n
      - passbolt
      - portainer

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    volumes:
      - /data/homelab/server_monitoring/grafana/data:/var/lib/grafana
    networks:
      - server-monitoring

networks:
  server-monitoring:
    name: server-monitoring
    external: true
  adguard:
    name: adguard_default
    external: true
  n8n:
    name: n8n_default
    external: true
  passbolt:
    name: passbolt_default
    external: true
  portainer:
    name: portainer_default
    external: true
